export const ratingValue = {
	"-": 0,
	"C-": 1,
	"C": 2,
	"C+": 3,
	"B-": 4,
	"B": 5,
	"B+": 6,
	"A-": 7,
	"A": 8,
	"A+": 9,
	"S-": 10,
	"S": 11,
	"S+": 12,
};

export const fmpSector = [
	"All",
	"Basic Materials",
	"Building",
	"Communication Services",
	"Conglomerates",
	"Consumer Cyclical",
	"Consumer Defensive",
	"Energy",
	"Financial",
	"Financial Services",
	"Healthcare",
	"Industrial Goods",
	"Industrials",
	"Media",
	"Pharmaceuticals",
	"Real Estate",
	"Services",
	"Technology",
	"Utilities",
];

export const fmpIndustry = [
	"All",
	"Advertising & Marketing Services",
	"Advertising Agencies",
	"Aerospace & Defense",
	"Agricultural Inputs",
	"Airports & Air Services",
	"Apparel Manufacturing",
	"Apparel Retail",
	"Apparel Stores",
	"Asset Management",
	"Auto & Truck Dealerships",
	"Auto Dealerships",
	"Auto Manufacturers",
	"Auto Parts",
	"Automobiles & Components",
	"Banks Diversified",
	"Banks Regional",
	"Beverages Alcoholic",
	"Beverages Brewers",
	"Beverages Non-Alcoholic",
	"Beverages Wineries & Distilleries",
	"Brokers & Exchanges",
	"Building Materials",
	"Building Products & Equipment",
	"Business Equipment & Supplies",
	"Business Services",
	"Capital Goods",
	"Capital Markets",
	"Closed-End Fund Debt",
	"Coking Coal",
	"Commercial  & Professional Services",
	"Communication Equipment",
	"Communication Services",
	"Computer Hardware",
	"Consulting & Outsourcing",
	"Consulting Services",
	"Consumer Electronics",
	"Consumer Packaged Goods",
	"Consumer Services",
	"Credit Services",
	"Department Stores",
	"Diagnostics & Research",
	"Discount Stores",
	"Diversified Financials",
	"Drug Manufacturers General Specialty & Generic",
	"Drug Manufacturers General",
	"Education & Training Services",
	"Electrical Equipment & Parts",
	"Electronic Components",
	"Electronic Gaming & Multimedia",
	"Electronics & Computer Distribution",
	"Electronics Wholesale",
	"Employment Services",
	"Engineering & Construction",
	"Farm & Construction Machinery",
	"Farm & Heavy Construction Machinery",
	"Farm Products",
	"Financial Conglomerates",
	"Financial Data & Stock Exchanges",
	"Food Distribution",
	"Food, Beverage & Tobacco",
	"Footwear & Accessories",
	"Forest Products",
	"Furnishings, Fixtures & Appliances",
	"Grocery Stores",
	"Health Care Equipment & Services",
	"Health Care Plans",
	"Health Care Providers",
	"Health Information Services",
	"Home Improvement Retail",
	"Homebuilding & Construction",
	"Household & Personal Products",
	"Independent Oil & Gas",
	"Industrial Distribution",
	"Industrial Electrical Equipment",
	"Industrial Metals & Minerals",
	"Industrial Products",
	"Information Technology Services",
	"Infrastructure Operations",
	"Insurance Brokers",
	"Insurance Diversified",
	"Insurance Life",
	"Insurance Property & Casualty",
	"Insurance Reinsurance",
	"Insurance Specialty",
	"Integrated Freight & Logistics",
	"Internet Content & Information",
	"Internet Retail",
	"Lumber & Wood Production",
	"Luxury Goods",
	"Manufacturing Apparel & Furniture",
	"Marine Shipping",
	"Media & Entertainment",
	"Medical Care Facilities",
	"Medical Devices",
	"Medical Diagnostics & Research",
	"Medical Distribution",
	"Medical Instruments & Equipment",
	"Medical Instruments & Supplies",
	"Metal Fabrication",
	"Metals & Mining",
	"Mortgage Finance",
	"Mortgage Investment",
	"Oil & Gas Drilling",
	"Oil & Gas E&P",
	"Oil & Gas Equipment & Services",
	"Oil & Gas Integrated",
	"Oil & Gas Midstream",
	"Oil & Gas Refining & Marketing",
	"Oil & Gas Services",
	"Online Media",
	"Other Industrial Metals & Mining",
	"Other Precious Metals & Mining",
	"Packaged Foods",
	"Packaging & Containers",
	"Paper & Paper Products",
	"Personal Services",
	"Pharmaceutical Retailers",
	"Pharmaceuticals, Biotechnology & Life Sciences",
	"Pollution & Treatment Controls",
	"Property Management",
	"REIT Diversified",
	"REIT Healthcare Facilities",
	"REIT Hotel & Motel",
	"REIT Industrial",
	"REIT Mortgage",
	"REIT Office",
	"REIT Residential",
	"REIT Retail",
	"REIT Specialty",
	"Real Estate Development",
	"Real Estate Diversified",
	"Real Estate Services",
	"Real Estate",
	"Recreational Vehicles",
	"Rental & Leasing Services",
	"Residential Construction",
	"Resorts & Casinos",
	"Retail Apparel & Specialty",
	"Retail Defensive",
	"Scientific & Technical Instruments",
	"Security & Protection Services",
	"Semiconductor Equipment & Materials",
	"Shell Companies",
	"Software & Services",
	"Software Application",
	"Software Infrastructure",
	"Specialty Business Services",
	"Specialty Chemicals",
	"Specialty Industrial Machinery",
	"Specialty Retail",
	"Staffing & Employment Services",
	"Telecom Services",
	"Textile Manufacturing",
	"Thermal Coal",
	"Tobacco Products",
	"Tools & Accessories",
	"Transportation & Logistics",
	"Travel & Leisure",
	"Travel Services",
	"Utilities Diversified",
	"Utilities Independent Power Producers",
	"Utilities Regulated Electric",
	"Utilities Regulated Gas",
	"Utilities Regulated Water",
	"Utilities Regulated",
	"Utilities Renewable",
	"Waste Management",
];

export default {
	ratingValue,
	fmpSector,
	fmpIndustry,
};