version: '3.6'

services:
  front-end:
    container_name: front-end
    image: front-end
    ports:
      - 5000:5000
    volumes:
      - front-end:/Stock_Project/front-end
    env_file: .env
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_HOST: ${REACT_APP_BACKEND_HOST}
        REACT_APP_BACKEND_HOST_FOR_SOCKET: ${REACT_APP_BACKEND_HOST_FOR_SOCKET}
        REACT_APP_FINANCIAL_MODELING_PREP_API_KEY: ${REACT_APP_FINANCIAL_MODELING_PREP_API_KEY}
        REACT_APP_FIREBASE_API_KEY: ${REACT_APP_FIREBASE_API_KEY}
        REACT_APP_FIREBASE_AUTH_DOMAIN: ${REACT_APP_FIREBASE_AUTH_DOMAIN}
        REACT_APP_FIREBASE_DATABASE_URL: ${REACT_APP_FIREBASE_DATABASE_URL}
        REACT_APP_FIREBASE_PROJECT_ID: ${REACT_APP_FIREBASE_PROJECT_ID}
        REACT_APP_FIREBASE_STORAGE_BUCKET: ${REACT_APP_FIREBASE_STORAGE_BUCKET}
        REACT_APP_NODE_ENV: ${REACT_APP_NODE_ENV}

volumes:
  front-end:
